Updates for DevPreview (try#3)
forcedotcom/sf-fx-sdk-nodejs pull request #35
Opened 2020-01-24 04:40 UTC by dhagberg-sf

Reference: https://salesforce.quip.com/sezcAUMykr7X

note each checklist item is (mostly) in individual commits to be able to review them separately.  Can squash merge if desired when merging to develop branch.

- [X] Remove Context.payloadVersion.
- N/A ~Remove Context.apiVersion.~ (skipped: doc indicates we need this for setting API version of API calls back to core)
- [X] Remove direct access to composite-api (moved to unit-of-work package, not exported from that index.ts - hopefully sufficient?)
- [x] Migrate to eslint (tslint deprecated). (may need to defer until we have eslint rules from sfdx?)
- [x] Migrate to yarn (package-lock.json => yarn.lock) for dependencies and build tasks
- [X] Move `lib/` to `src/`
- [x] Make tsp output to `lib/`, have node package lib output, per @jqian2017 
- [x] Use/import `@salesforce/core` as `jsforce` API layer
- [x] Use/import `@salesforce/core` as `Logger` impl
- [x] Default typed jsforce API return objects to SDK’s classes.
- [X] `package.json` description to "Salesforce SDK for Node.js"
- [X] cloudevents dependency - looks like we can remove this, not referenced in source or transitives - can import later as 1.0.0 which includes types.

Doc has more discussion and follow-on work for subsequent PRs.

Will drop WIP label once ready for deeper review

2020-01-28 15:42 UTC, cwallsfdc requested changes
Awesome first contribution!  A few requests.

2020-01-28 22:57 UTC, cwallsfdc submitted a review, later dismissed
Just question about updating a test to use SObject when calling `forceApi` method.

2020-01-29 18:21 UTC, jleen-sfdc submitted a review, later dismissed

2020-01-29 21:26 UTC, jqian2017 submitted a review, later dismissed

2020-01-29 22:33 UTC, cwallsfdc approved these changes
After merging, please (a) publish to npm and (b) update all references to the latest.  Thank you.

2020-01-29 22:36 UTC, merged